### ISSUE TITLE
Sparkle works only in page wrapper

### ISSUE THREAD

**Issue by DavesBrain** [marzepani/sparkle-js#1]
This may be operating as-designed - I am not sure.

Sparkle-js seems set up to only work in the very outer wrapper, on the document background. I was hoping to use it to fill just one box (slide in a vertical slide show), located below the fold on the page. 

Other sparklers are too heavy. This one is very light. Which is why I'm preferring it.

**Comment by marzepani** [comment]
Yes, sparkle-js was designed to work that way.

**Comment by virginielgb** [comment]
@DavesBrain otherwise maybe you can use that http://jsfiddle.net/virginieLGB/mL6uf3xm/6/embedded/
which I did based on sparkle-js and completely readapted for what I wanted ;)
